# Generated by Django 2.1.7 on 2019-04-04 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=80)),
                ('nome_fantasia', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=14)),
                ('inscricao_estadual', models.CharField(max_length=14)),
                ('contato', models.CharField(max_length=60)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2)),
                ('planos_internet', models.ManyToManyField(to='main.PlanoInternet')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='VelocidadeInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tipo_acesso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.TipoAcesso'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='velocidades_internet',
            field=models.ManyToManyField(to='main.VelocidadeInternet'),
        ),
    ]
