# Generated by Django 2.1.7 on 2019-04-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parceiro',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='tipo_acesso_id',
            new_name='tipo_acesso',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
