# Generated by Django 2.1.7 on 2019-04-22 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190410_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parceiro',
            options={'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AlterModelOptions(
            name='planointernet',
            options={'verbose_name': 'Plano de Internet', 'verbose_name_plural': 'Plano de Internet'},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AlterModelOptions(
            name='tipoacesso',
            options={'verbose_name': 'Tipo de acesso', 'verbose_name_plural': 'Tipos de acesso'},
        ),
        migrations.AlterModelOptions(
            name='velocidadeinternet',
            options={'verbose_name': 'Velocidade de Internet', 'verbose_name_plural': 'Velocidades de Internet'},
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='inscricao_estadual',
            field=models.CharField(max_length=14, verbose_name='Inscrição estadual'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='razao_social',
            field=models.CharField(max_length=80, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='planos_internet',
            field=models.ManyToManyField(to='main.PlanoInternet', verbose_name='Planos de internet'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo_acesso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.TipoAcesso', verbose_name='Tipo de acesso'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='velocidades_internet',
            field=models.ManyToManyField(to='main.VelocidadeInternet', verbose_name='Velocidades de internet'),
        ),
    ]
