# Generated by Django 2.1.7 on 2019-04-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190422_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='complemento',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
