# Generated by Django 2.1.7 on 2019-04-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190422_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='complemento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
