# Generated by Django 2.2 on 2019-05-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190424_2141'),
        ('main', '0006_auto_20190426_2007'),
    ]

    operations = [
    ]
