# Generated by Django 2.1.7 on 2019-05-08 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20190424_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=300)),
                ('valor_implantacao', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor de implantação')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor de mensalidade')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='observacoes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Solicitacao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
