# Generated by Django 2.1.7 on 2019-05-10 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190507_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='inativo',
            field=models.BooleanField(default=False, verbose_name='Inativo'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='parceiro_escolhido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Parceiro'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='main.Solicitacao'),
        ),
    ]
