# Generated by Django 2.2 on 2019-05-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20190503_1951'),
        ('main', '0009_auto_20190509_2014'),
    ]

    operations = [
    ]
